[package]
name = "abs"
version = "0.1.0"
authors = ["maedana <maeda.na@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
